-- MySQL Script generated by MySQL Workbench
-- Wed Jun 22 17:09:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
-- Blog P5 François Tanguy Guillo — 21 juin 2022

-- -----------------------------------------------------
-- Schema blog
--
-- Blog P5 François Tanguy Guillo — 21 juin 2022
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`user` ;

CREATE TABLE IF NOT EXISTS `blog`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `EmailUser` VARCHAR(255) NULL,
  `passWordUser` VARCHAR(42) NULL COMMENT 'to do : encrypt',
  `nameUser` VARCHAR(70) NULL,
  `surNameUser` VARCHAR(70) NULL,
  `titleUser` ENUM('Madam', 'Miss', 'Mister') NULL,
  `telGsmUser` VARCHAR(45) NULL,
  `roleUser` ENUM('Admin', 'User') NULL,
  `pictureOrLogo` VARCHAR(512) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`blog_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`blog_post` ;

CREATE TABLE IF NOT EXISTS `blog`.`blog_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `postTitle` VARCHAR(255) NULL,
  `postChapo` LONGTEXT NULL,
  `postContent` LONGTEXT NULL,
  `postCreated` DATETIME NOT NULL,
  `postStatus` ENUM('Waiting for validation', 'Open', 'Closed') NULL,
  `postName` VARCHAR(255) NULL,
  `postModified` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_blog_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_blog_post_user1_idx` ON `blog`.`blog_post` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `blog`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`comment` ;

CREATE TABLE IF NOT EXISTS `blog`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CommentCreated` DATETIME NULL,
  `commentStatus` ENUM('Waiting for validation', 'open', 'Closed', 'Refuse') NULL,
  `commentContent` LONGTEXT NULL,
  `user_id` INT NOT NULL,
  `blog_post_id` INT NOT NULL,
  `blog_post_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `blog_post_id`, `blog_post_user_id`),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_blog_post1`
    FOREIGN KEY (`blog_post_id` , `blog_post_user_id`)
    REFERENCES `blog`.`blog_post` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comment_user1_idx` ON `blog`.`comment` (`user_id` ASC);

CREATE INDEX `fk_comment_blog_post1_idx` ON `blog`.`comment` (`blog_post_id` ASC, `blog_post_user_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
